// frontend/src/components/orders/OrderBoard.tsx
import { useState } from 'react';
import StatusSection from './StatusSection';
import { OrderStatus } from './OrderCard';

const STATUSES: OrderStatus[] = ['DELIVERY', 'COORDINATE', 'BACKYARD'];

export default function OrderBoard() {
  const [selectedOrderId, setSelectedOrderId] = useState<string | null>(null);

  return (
    <div className="grid min-h-screen grid-cols-1 gap-4 bg-gray-100 p-4 md:grid-cols-[380px_1fr]">
      <aside className="space-y-4">
        {STATUSES.map((status) => (
          <StatusSection
            key={status}
            status={status}
            selectedOrderId={selectedOrderId}
            onSelectOrder={setSelectedOrderId}
          />
        ))}
      </aside>

      <main className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
        <h2 className="mb-2 text-lg font-semibold text-gray-900">Order Detail</h2>
        <p className="text-sm text-gray-600">
          {selectedOrderId
            ? `Selected order id: ${selectedOrderId}`
            : '詳細表示エリア（プレースホルダー）'}
        </p>
      </main>
    </div>
  );
}

// frontend/src/components/orders/OrderBoard.vue
<template>
  <div class="order-board">
    <aside class="status-column">
      <StatusSection
        v-for="status in statuses"
        :key="status"
        :status="status"
        :selected-order-id="selectedOrderId"
        @select-order="selectedOrderId = $event"
      />
    </aside>

    <main class="order-detail">
      <h2 class="order-detail-title">Order Detail</h2>
      <p class="order-detail-text">
        {{ selectedOrderId ? `Selected order id: ${selectedOrderId}` : "詳細表示エリア（プレースホルダー）" }}
      </p>
    </main>
  </div>
</template>

<script setup>
import { ref } from "vue";
import StatusSection from "./StatusSection.vue";

const statuses = ["DELIVERY", "COORDINATE", "BACKYARD"];
const selectedOrderId = ref(null);
</script>

<style scoped>
.order-board {
  min-height: 100vh;
  display: grid;
  grid-template-columns: 1fr;
  gap: 16px;
  padding: 16px;
  background: #f3f4f6;
}

.status-column {
  display: grid;
  gap: 16px;
}

.order-detail {
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  background: #fff;
  padding: 24px;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04);
}

.order-detail-title {
  margin: 0 0 8px;
  font-size: 18px;
  color: #111827;
}

.order-detail-text {
  margin: 0;
  font-size: 14px;
  color: #4b5563;
}

@media (min-width: 960px) {
  .order-board {
    grid-template-columns: 380px 1fr;
  }
}
</style>
